//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BancoRecursoGlosaEntities : DbContext
    {
        public BancoRecursoGlosaEntities()
            : base("name=BancoRecursoGlosaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEMONSTRATIVO> DEMONSTRATIVO { get; set; }
        public virtual DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public virtual DbSet<GUIAS> GUIAS { get; set; }
        public virtual DbSet<LOTE> LOTE { get; set; }
        public virtual DbSet<OPERADORAS> OPERADORAS { get; set; }
        public virtual DbSet<PRESTADORES> PRESTADORES { get; set; }
        public virtual DbSet<PRESTADORES_has_OPERADORAS> PRESTADORES_has_OPERADORAS { get; set; }
        public virtual DbSet<PROCEDIMENTO> PROCEDIMENTO { get; set; }
        public virtual DbSet<RECURSO_GLOSA> RECURSO_GLOSA { get; set; }
        public virtual DbSet<TABELA_ANS> TABELA_ANS { get; set; }
        public virtual DbSet<TABELA_OPCOES_ANS> TABELA_OPCOES_ANS { get; set; }
    }
}
