
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Teste.Database
{

using System;
    using System.Collections.Generic;
    
public partial class DEMONSTRATIVO
{

    public int ID_DEMONS { get; set; }

    public int PRESTADORES_has_OPERADORAS_OPERADORAS_ID_OPERADORA { get; set; }

    public int PRESTADORES_has_OPERADORAS_PRESTADORES_IDPRESTADOR { get; set; }

    public int FUNCIONARIO_ID_FUNCIONARIO { get; set; }

    public Nullable<System.DateTime> DT_BAIXADO { get; set; }

    public Nullable<int> TIP_DEMONS { get; set; }



    public virtual FUNCIONARIO FUNCIONARIO { get; set; }

    public virtual PRESTADORES_has_OPERADORAS PRESTADORES_has_OPERADORAS { get; set; }

}

}
