//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCIONARIO()
        {
            this.DEMONSTRATIVO = new HashSet<DEMONSTRATIVO>();
            this.RECURSO_GLOSA = new HashSet<RECURSO_GLOSA>();
        }
    
        public int ID_FUNCIONARIO { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
        public string NOME_FUNCIONARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEMONSTRATIVO> DEMONSTRATIVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECURSO_GLOSA> RECURSO_GLOSA { get; set; }
    }
}
