
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Teste.Database
{

using System;
    using System.Collections.Generic;
    
public partial class GUIAS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GUIAS()
    {

        this.PROCEDIMENTO = new HashSet<PROCEDIMENTO>();

    }


    public int ID_GUIA { get; set; }

    public Nullable<int> LOTE_COD_LOTE { get; set; }

    public Nullable<int> COD_GUIA { get; set; }

    public Nullable<int> PROTOCOLO { get; set; }

    public Nullable<int> NUM_GUIA { get; set; }

    public Nullable<int> NUM_GUIA_PRESTADOR { get; set; }

    public Nullable<int> SENHA { get; set; }



    public virtual LOTE LOTE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PROCEDIMENTO> PROCEDIMENTO { get; set; }

}

}
