
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Teste.Database
{

using System;
    using System.Collections.Generic;
    
public partial class OPERADORAS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OPERADORAS()
    {

        this.PRESTADORES_has_OPERADORAS = new HashSet<PRESTADORES_has_OPERADORAS>();

        this.TABELA_OPCOES_ANS = new HashSet<TABELA_OPCOES_ANS>();

    }


    public int ID_OPERADORA { get; set; }

    public string NOME_FANTASIA { get; set; }

    public Nullable<int> REGISTRO_ANS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRESTADORES_has_OPERADORAS> PRESTADORES_has_OPERADORAS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABELA_OPCOES_ANS> TABELA_OPCOES_ANS { get; set; }

}

}
