
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Teste.Database
{

using System;
    using System.Collections.Generic;
    
public partial class PRESTADORES
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PRESTADORES()
    {

        this.PRESTADORES_has_OPERADORAS = new HashSet<PRESTADORES_has_OPERADORAS>();

    }


    public int IDPRESTADOR { get; set; }

    public string RAZAO_SOCIAL { get; set; }

    public string CPF_CNPJ { get; set; }

    public string NOME_FANTASIA { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRESTADORES_has_OPERADORAS> PRESTADORES_has_OPERADORAS { get; set; }

}

}
