//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECURSO_GLOSA
    {
        public int idRECURSO_GLOSA { get; set; }
        public Nullable<int> TABELA_ANS_COD_ANS { get; set; }
        public Nullable<int> TABELA_OPCOES_ANS_ID_OPCOES { get; set; }
        public int PROCEDIMENTO_idPROCEDIMENTO { get; set; }
        public int PRESTADORES_has_OPERADORAS_OPERADORAS_ID_OPERADORA { get; set; }
        public int PRESTADORES_has_OPERADORAS_PRESTADORES_IDPRESTADOR { get; set; }
        public int FUNCIONARIO_ID_FUNCIONARIO { get; set; }
        public string OBSERVACAO { get; set; }
        public Nullable<int> STATUS_2 { get; set; }
        public Nullable<double> VLR_RECURSADO { get; set; }
        public Nullable<System.DateTime> DT_RECURSO { get; set; }
        public Nullable<System.DateTime> DPP { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual PRESTADORES_has_OPERADORAS PRESTADORES_has_OPERADORAS { get; set; }
        public virtual PROCEDIMENTO PROCEDIMENTO { get; set; }
        public virtual TABELA_OPCOES_ANS TABELA_OPCOES_ANS { get; set; }
        public virtual TABELA_ANS TABELA_ANS { get; set; }
    }
}
