//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABELA_OPCOES_ANS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TABELA_OPCOES_ANS()
        {
            this.RECURSO_GLOSA = new HashSet<RECURSO_GLOSA>();
            this.TABELA_ANS = new HashSet<TABELA_ANS>();
        }
    
        public int ID_OPCOES { get; set; }
        public Nullable<int> OPERADORAS_ID_OPERADORA { get; set; }
        public string DESCRIÇÃO { get; set; }
        public Nullable<int> COD_INTERNO { get; set; }
        public string RESPOSTA_AUTOMATICA { get; set; }
    
        public virtual OPERADORAS OPERADORAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECURSO_GLOSA> RECURSO_GLOSA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABELA_ANS> TABELA_ANS { get; set; }
    }
}
